### ISSUE TITLE
[Tracking] Prepare official release 2.0

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redoc#1292]
We've had release candidates available for 2 years. They're in use by thousands of companies. They are solid and stable. However, I know we held off on making an official release.

I propose we work these issues and at the conclusion make the official release.

- [ ] Use `openapi-cli` under the hood (blocked by https://github.com/Redocly/openapi-cli/issues/142)
- [ ] https://github.com/Redocly/redoc/issues/1279 Fix accessibility issues 
- [ ] https://github.com/Redocly/redoc/issues/437 Add support for links (or consider it)
- [ ] https://github.com/Redocly/redoc/issues/1291 Update the README

Are there any other issues that should be considered prior to the official release?

**Comment by chatelao** [comment]
I love links and could assist in design if needed.

**Comment by adamaltman** [comment]
@chatelao go ahead and post any ideas into #437 please. Thank you!
